# Generated by Django 3.1.4 on 2024-02-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.BigIntegerField()),
                ('User_Name', models.CharField(max_length=255)),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_Password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='User_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user_credentials'),
        ),
    ]
