# Generated by Django 3.1.4 on 2024-02-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20240207_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_credentials',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_credentials',
            name='User_Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
