# Generated by Django 3.1.4 on 2024-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20240207_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='Email_Address',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='Username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
