# Generated by Django 3.1.4 on 2024-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20240207_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='Email_Address',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='Username',
            field=models.CharField(max_length=20),
        ),
    ]
